### ISSUE TITLE
Taalfoutje in beeld na klikken op concept opslaan

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Forum#1]
Na klikken op concept opslaan (bij het opstellen van een bericht) komt er een melding in beeld die een storende taalfout bevat:
![afbeelding](https://cloud.githubusercontent.com/assets/21307438/24741384/f4e59438-1aa5-11e7-947c-8f7106931201.png)

**Comment by HansNien** [comment]
Hmm. Dat oogt wel heel zuid-afrikaans. Die vertaling heb ik ook niet gemaakt. Hij staat niet in common.php, het bestand waarin de jargonvertalingen zijn opgenomen. Mark, heb jij een idee in welk bestand deze zin dan wel kan staan?

**Comment by coreice** [comment]
Als het goed is staan de vertaling voor o.a. concepten in `posting.php` (onder `../language/nl/`). Dan moet je de sleutel `SAVE_DRAFT_CONFIRM` aanpassen als ik mij niet vergis.

**Comment by HansNien** [comment]
FIXED.
