### ISSUE TITLE
Templatekleuren in lijn brengen met de mainsite en de netkaart

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#2]
Aangezien ColorizeIt het niet meer doet voor phpBB 3.2, zal dit handmatig moeten gebeuren met behulp van CSS. Dat wordt leuk voor uw kleurendove medemens (%&#"§#!), zodat hier enige tijd in gaat zitten en het wellicht een proefopstelling vraagt. 

- [x] Templatekleuren in stijl brengen

- [x] Pictogrammen gelezen/ongelezen iets duidelijker de aandacht laten trekken

- [x] Gebruikersnamen forumleden in profiel naast de berichten in een (iets) groter font weergeven

- [x] Headerafbeelding toevoegen en functioneel maken

**Comment by coreice** [comment]
Updates zijn er ook niet te verwachten bij ColorizeIt, ze laten de ondersteuning voor phpBB (helaas) compleet vallen.

**Comment by HansNien** [comment]
Ter indicatie, een idee zoals ik dat zelf heb over de uiteindelijke kleurmodificaties, toegepast op de voorpagina. 
Er zijn geen fancy 'nieuwe' kleurenschema's beraamd met een verloop: de omkasting van de subfora zou niet lichter naar beneden toe moeten worden, maar gewoon hard #2D5A9F. Dat is in lijn met de versimpelde stijl van de mainsite (waar we eveneens verloopjes gesloopt hebben en op twee hoofdkleuren vertrouwen). Verder is de informatiebalk in dit voorbeeld lichtgroen gemaakt, overeenkomend met de submenukleuren op de mainsite. Mouseover (demo op het netkaartsubforum) kan dezelfde kleur hebben. Pictogrammen voor nieuwe berichten zijn in prosilver vrij onduidelijk, die wil ik een beetje oppompen. Dat is eenvoudig te verbouwen omdat het gewoon een transparante GIF is, al dan niet geanimeerd (nabouwen). De rest van de achtergronden van de subfora kan gewoon zo blijven als het is, dat scheelt. Details daargelaten, zoals mouseovers.

![mock-up forum met header en kleurmod](https://cloud.githubusercontent.com/assets/23345566/24745701/e4407786-1ab6-11e7-916f-743c393041a3.JPG)

Het zal niet meteen overnacht gefixt zijn, maar dit moet te doen zijn. Op de header na vereist het alleen wat stoeien met de CSS en het verbouwen van enkele PNG's. We hebben voor hetere vlambogen gestaan.

**Comment by BaDu-HSN** [comment]
Kijk aan dat ziet er al een heel stuk beter uit :)

**Comment by HansNien** [comment]
Gebruikersnamen staan nu op 1.3em en de tussenruimte is ook wat vergroot. Font is bold gezet. Ziet er zo strak uit als de geleiders van een afgeschakelde wintrackverbinding bij min tien.

**Comment by coreice** [comment]
Oef, het citaatgedeelte spat wel erg van mijn scherm. Dat zou wat mij betreft een tikkeltje teruggeschakeld mogen worden :p. 

![schermafbeelding 2017-04-07 om 19 34 34](https://cloud.githubusercontent.com/assets/10442497/24812183/5d2fb41e-1bc9-11e7-8e27-3b474fd2f9a6.png)

**Comment by HansNien** [comment]
Dank voor de terugkoppeling. (En zie hier de valkuil van kleurenblinden, voor mij is ie helemaal niet zo fel van kleur, ik zie dat soort dingen gewoon niet zo best.) Momentje, ik schroef hem wat omlaag.

**Comment by coreice** [comment]
Ik zie het, inderdaad stukken beter zo 👍

**Comment by HansNien** [comment]
Inmiddels zijn dan ook uiteindelijk de pictogrammen aangepast. De CSS is vrijwel gereed, hoewel er hier en daar vast nog wel een verkleerd kleurtje of een niet aangepast icoon rondzwerft. Die worden ad-hoc of op verzoek opgelost (nieuw item aanmaken), in grote lijn is de operatie gereed. Deze kan gesloten worden.
