### ISSUE TITLE
Toevoegen header met headermenu

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#3]
Headerafbeelding maken met logo en een headermenu zoals dat bijvoorbeeld ook aanwezig is op het eigen forum van phpBB Nederland. Er kan dan direct naar essentiële links worden verwezen, waaronder de mainsite en de netkaart.

**Comment by coreice** [comment]
Dit valt op verschillende manieren uit te leggen. Zie je een verregaande integratie van het forum in de website voor je zoals op phpbb.nl of phpbb.com, waarbij je dus continu dezelfde header bovenaan hebt staan? Of simpelweg gewoon wat linkjes?

**Comment by HansNien** [comment]
Over dit punt heb ik een vraag gesteld op het phpBB-forum en reeds enig advies ontvangen. Hou als leidraad de header van phpbb.nl maar aan. Verregaande integratie is voorlopig niet aan de orde omdat het forum en de website op twee verschillende URLs draaien en er geen behoefte is om dat te wijzigen - ook niet vanwege de 3000 bestaande fotolinks vanuit de netkaart. 

Ik zat gewoon te denken aan een header die er een beetje knap uitziet, met daaronder een menubalk in de huisstijl waar links in staan die naar externe plekken verwijzen zoals de mainsite en de online netkaart (op termijn).

Mock-up:

![mock-up forum met header](https://cloud.githubusercontent.com/assets/23345566/24744224/8c439914-1ab1-11e7-8e07-fe563439904f.JPG)

Punt van aandacht is dat de afbeelding dynamisch schalen moet toestaan. Daar zal ik nog eens in moeten duiken, maar dat staat los van het menu. Die kan rechts gewoon breder en smaller worden.

**Comment by coreice** [comment]
Top. Lijkt mij een prima toevoeging (en heb het draadje gespot op phpBB.nl).

**Comment by BaDu-HSN** [comment]
De afbeelding is echt prima zo, alleen de tekst bovenin is wel wat conservatief: Forum over het nederlandse en belgische hoogspanningsnet.

Graag deze algemener stellen aangezien we steeds meer de grens over gaan, bijvoorbeeld:
"Forum over hoogspanning" of "Forum over ons hoogspanningsnet"

**Comment by HansNien** [comment]
Nog geen pure perfectie, maar het komt dichtbij genoeg om dit topic te sluiten.
