### ISSUE TITLE
Wit scherm na posten bericht

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#4]
Soms (niet altijd helaas) verschijnt een volledig wit scherm na het posten van een bericht, terwijl het bericht zelf probleemloos geplaatst wordt. In geen enkel geval verschijnt echter de bevestiging dat je een bericht hebt geplaatst die normaliter enkele seconden in beeld zou moeten zijn. Vermoedelijk gaat het hier mis.

**Comment by HansNien** [comment]
Hiervoor heb ik een ticket ingeschoten bij phpbb.nl. Eens zien wat de experts ervan denken.

**Comment by coreice** [comment]
Prima, ik heb geen flauw idee eigenlijk. Zonder foutmelding is het echt heel lastig een opstij.. aanknopingspunt te vinden.

**Comment by HansNien** [comment]
Vooralsnog weinig progressie. Ik snap er ook niets van dat ie de ene keer zonder problemen het bericht post en niet blijft hangen in een wit scherm, terwijl dat een andere keer zomaar wel gebeurt. En dat bevestigingsscherm blijkt bij het posten van een bericht tegenwoordig te worden overgeslagen (kennelijk is die er alleen nog als je je profiel aanpast), zie ook de reactie van iemand op het phpBB-forum. Maar de zaak an sich wordt er niet anders van. Juist het feit dat ie het soms wel en soms niet doet maakt het ongrijpbaar: de suggestie van een missend bestand klopt dan niet.

**Comment by HansNien** [comment]
Bij de meest recente witscherm-error heb ik de broncode eens opgevraagd. Behalve een leeg HTML-bestand (is logisch bij een witte pagina) blijkt de broncode echter wel gewoon een viewtopic op te bouwen, onzichtbaar onder het witte scherm. Graven we dan even door, dan verschijnt vanaf regel 1300 dit ding:

`<div id="darkenwrapper" class="darkenwrapper" data-ajax-error-title="AJAX-kortsluiting" data-ajax-error-text="Er vond een kortsluiting plaats tijdens het verwerken van je aanvraag." data-ajax-error-text-abort="Aanvraag is afgebroken door de aangeslotene." data-ajax-error-text-timeout="Je aanvraag is verlopen; probeer het nog een keer." data-ajax-error-text-parsererror="Er ging iets mis met de aanvraag en de server stuurde een ongeldige reactie terug.">
		<div id="darken" class="darken">&nbsp;</div>
	</div>

	<div id="phpbb_alert" class="phpbb_alert" data-l-err="Kortsluiting" data-l-timeout-processing-req="Tijdslimiet voor aanvraag verstreken.">
		<a href="#" class="alert_close">
			<i class="icon fa-times-circle fa-fw" aria-hidden="true"></i>
		</a>
		<h3 class="alert_title">&nbsp;</h3><p class="alert_text"></p>
	</div>
	<div id="phpbb_confirm" class="phpbb_alert">
		<a href="#" class="alert_close">
			<i class="icon fa-times-circle fa-fw" aria-hidden="true"></i>
		</a>
		<div class="alert_text"></div>
	</div>
</div>`

AJAX laat het afweten. Los van dat ik dat graag eens zou zien op de grasmat, kan het best eens wezen dat dit ding ermee te maken heeft. Ik heb het in elk geval voorgelegd in het lopende topic op phpBB.nl.

**Comment by coreice** [comment]
"Tijdslimiet voor aanvraag verstreken"

Dat doet een probleem bij de database vermoeden.

**Comment by HansNien** [comment]
Toch vraag ik me bij nader inzien af of dit iets is. Bij het opvragen van de source van een gewone viewtopic zonder het posten van een bericht en waarbij de pagina volstrekt normaal op het scherm komt, verschijnt ook precies dezelfde AJAX-kortsluiting binnen een eigen div.

**Comment by coreice** [comment]
Is er nog nieuws van het phpbb.nl front, @HansNien ?

**Comment by HansNien** [comment]
https://www.phpbb.nl/forums/viewtopic.php?f=100&t=61093

Helaas, het is al een week stil. Maar zoals daar geschreven, het is zaak om bij het verschijnen van de error direct de broncode op te vragen en die te vergelijken met het scherm dat verschijnt als de error niet opspeelt. Daarna hebben we mogelijk een betere aanwijzing van waarom soms wél en waarom soms níet. Ik moet me daar alleen nog de tijd voor gunnen.

**Comment by BaDu-HSN** [comment]
De volgende foutmelding verschijnt na het aanztten van php foutmeldingen in posting.php:
``Fatal error: Uncaught Twig_Error_Loader: The "" directory does not exist. in /home/deb99417/domains/hoogspanningsforum.com/public_html/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:94 Stack trace: #0 /home/deb99417/domains/hoogspanningsforum.com/public_html/phpbb/template/twig/loader.php(110): Twig_Loader_Filesystem->addPath(false, '_main') #1 /home/deb99417/domains/hoogspanningsforum.com/public_html/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(76): phpbb\template\twig\loader->addPath('./language/nl_x...', 'main_') #2 /home/deb99417/domains/hoogspanningsforum.com/public_html/phpbb/template/twig/twig.php(236): Twig_Loader_Filesystem->setPaths(Array) #3 /home/deb99417/domains/hoogspanningsforum.com/public_html/includes/functions_messenger.php(697): phpbb\template\twig\twig->set_custom_style(Array, Array) #4 /home/deb99417/domains/hoogspanningsforum.com/public_html/includes/functions_messenger.php(281): messenger->set_template_paths(Array, Array) #5 /home/deb99417/domains/hoogspanningsforum.com/public_html/phpbb/n in /home/deb99417/domains/hoogspanningsforum.com/public_html/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 94``

**Comment by coreice** [comment]
En de ubersimpele fix was simpelweg een oud taalpakket (Nederlands, formeel) uit het ACP te slopen. phpBB dacht dat deze nog aanwezig was terwijl dit niet zo was (zelfde oplossing als toegepast in 2015 bij het Wegenforum).
