### ISSUE TITLE
Batch upload voor bijlagen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#5]
Lang geleden uitgesproken wens van Bavo. Batch upload ben ik enerzijds een beetje huiverig voor (het maakt het wel erg makkelijk om maar van alles erop te gooien), anderzijds gaat het al jaren goed qua uploads en lijkt de forumcultuur + strakke moderatie wel soelaas te bieden om de kans op uit de hand lopen klein te houden. Vereist aan de technische kant enig onderzoek naar extensies.

**Comment by coreice** [comment]
Deze mag je gelijk weer sluiten, per phpBB 3.1 zit dit al standaard ingebouwd :).

<img width="605" alt="schermafbeelding 2017-04-06 om 10 30 03" src="https://cloud.githubusercontent.com/assets/10442497/24744959/1f47c40e-1ab4-11e7-8254-4d5811ce5363.png">

**Comment by HansNien** [comment]
Waaaat? Nou, dat gaat snel dan. Kunnen we Shrek meteen blij maken.
