### ISSUE TITLE
Links openen in een nieuw venster

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#6]
Nieuwe links op het forum vanuit berichten laten openen in een nieuw venster. (Dat is reeds geprobeerd, maar het bleek op problemen uit te draaien zoals een wit scherm of links die twee keer getoond werden.) 

De beschrijving van phpBB om dit aan te passen werkt alleen voor nieuwe links. Bestaande links worden niet beïnvloed.

**Comment by coreice** [comment]
Wil hier vanavond wel even naar kijken.

**Comment by HansNien** [comment]
Graag. (Zelf zit ik de komende twee dagen met een voorziene niet-beschikbaarheid, maar als er wat definitief stuk mocht gaan zetten we gewoon de backup van een paar uur eerder terug.)

**Comment by HansNien** [comment]
Lijkt vooralsnog te werken Mark.

**Comment by coreice** [comment]
Top :). Heb een backup van de bestanden trouwens in de desbetreffende mappen staan (met als voorvoegsel `OLD_`).

**Comment by HansNien** [comment]
Ah, dank. Zo'n map heb ik ook op de lokale machine staan, maar dan onder de naam _orig_. Zelfde idee. Ik sluit vooralsnog dit item.
