### ISSUE TITLE
Favicon regelen

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Forum#7]
Klein dingetje, wel belangrijk.

**Comment by BaDu-HSN** [comment]
Zie favicons van de webkaart site
![favicon-0](https://cloud.githubusercontent.com/assets/21307438/24828830/8b5fc192-1c66-11e7-807f-90abd802b65f.png)
![favicon-1](https://cloud.githubusercontent.com/assets/21307438/24828834/8b6bd96e-1c66-11e7-932c-d806cf5f50c3.png)
![favicon-2](https://cloud.githubusercontent.com/assets/21307438/24828832/8b6a0210-1c66-11e7-953e-f33c2dd7e79c.png)
![favicon-3](https://cloud.githubusercontent.com/assets/21307438/24828831/8b69aaf4-1c66-11e7-84ad-045828ae5d91.png)
![favicon-4](https://cloud.githubusercontent.com/assets/21307438/24828833/8b6a616a-1c66-11e7-9e48-b2773df454f1.png)
![favicon-5](https://cloud.githubusercontent.com/assets/21307438/24828835/8b6c76da-1c66-11e7-9ce5-569d510769e8.png)

**Comment by HansNien** [comment]
Inmiddels het bovenste exemplaar netjes tot een .ico verbouwd, in de root gezet, overall_header aangepast, maar helaas doet ie precies net zoveel als een politicus op wachtgeld: niets. De URL zal wel niet deugen. Mark, als jij nog tijd hebt, kan jij eens een blik werpen?

**Comment by BaDu-HSN** [comment]
Het favicon wordt weergegeven met een witte vierkante achtergrond.
We hadden dat voor de webkaart al eens aangepast naar een rondje, strakker en mooier mi.

![afbeelding](https://cloud.githubusercontent.com/assets/21307438/24896003/4b65c6e8-1e93-11e7-90b6-698d58e657d5.png)

Hierbij dan ook meteen de favicon van de webkaart:
[favicon.zip](https://github.com/Hoogspanningsnet/Forum/files/912323/favicon.zip)

**Comment by HansNien** [comment]
Op het oude forum hadden we ook een favicon met een transparante achtergrond. Ik was er voor het gemak maar vanuit gegaan dat het kleinste exemplaar in de meegestuurde reeks dat ook al had. Oeps, iets te snel gedacht dus. Dank voor de zipmap, ik wissel het geladen .ico bestandje dadelijk even om. Inderdaad is de cirkel met witte achtergrond een stuk fraaier.

Overigens wordt ie hier (FF in Win7) nog steeds niet weergegeven. Ik had dus helemaal niet in de gaten dat hij het blijkbaar bij andere mensen wel doet.

Edit: nieuw icoon ingevoegd. Ik kan zo gauw hier niet controleren of ie werkt, want zowel in FF als in Chrome verschijnt de afbeelding niet, ook niet na het legen van de cache.

**Comment by coreice** [comment]
Zou gefixed moeten wezen. Wil nog even kijken naar extra icoontjes.

**Comment by HansNien** [comment]
Laten we voor extra iconen maar een aparte discussie aanmaken. Het favicon doet het hier nu eindelijk ook (het lijkt de Drentse heide wel) en het ziet er prima uit. Dank, deze kunnen we sluiten.
